site_name: Wyrm Suite Documentation

theme: readthedocs

nav:
  - "Home page": 'index.md'
  - "Wyrm":
    - "Comments": "wyrm/comments.md"
    - "Types": "wyrm/types.md"
    - "Variables": "wyrm/variables.md"
    - "Conditionals": "wyrm/conditionals.md"
    - "Loops": "wyrm/loops.md"
    - "Functions": "wyrm/functions.md"
  - "Phi":
    - ""
  - "Drac":
    - ""
  - "Zmey":
    - ""
markdown_extensions:
  - markdown.extensions.admonition
extra_css:
  - overrides/css/extra.css